name: database-tests
on: [push, pull_request]
jobs:
  pgtap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start -x studio,imgproxy,inbucket,edge-runtime,logflare,vector,realtime
      - run: supabase db reset
      - run: supabase test db
